name: Android build
on:
  push:
    branches:
      - test-workflow
jobs:
  run-build:
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Install Android SDK with pieces Gradle skips
        run: ./automation/install-sdk.sh
      - name: Create version name
        run: echo "VERSION_NAME=$(git describe --tags HEAD)" >> $GITHUB_ENV
      - name: Build variant of app
        uses: eskatos/gradle-command-action@v1
        with:
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
          arguments: app:assembleDebug -PversionName=102 # -PversionName=${{ env.VERSION_NAME }}
      - name: Create signed APKs
        id: sign_app
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/debug/
          signingKeyBase64: ${{ secrets.SIGNING_KEY_BASE64 }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEYSTORE_PASSWORD }}
      # - name: List outputs after signing
      #   run: find /home/runner/ -name '*.apk' || true
      - name: Archive apks
        uses: actions/upload-artifact@v3
        with:
          path: app/build/outputs/apk/debug/app-*-signed.apk
