name: Android build
on:
  push:
    branches:
      - test-workflow
jobs:
  run-build:
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Install Android SDK with pieces Gradle skips
        run: ./automation/install-sdk.sh
      - name: Create version name
        run: echo "VERSION_NAME=$(git describe --tags HEAD)" >> $GITHUB_ENV
      - name: Build variant of app
        uses: eskatos/gradle-command-action@v1
        with:
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
          arguments: app:assembleDebug -PversionName=102 # -PversionName=${{ env.VERSION_NAME }}
      - name: List outputs
        run: ls app/build/outputs/**/*
      - name: Create signed APKs
        uses: abhijitvalluri/sign-apks@v0.8
        with:
          releaseDirectory: app/build/outputs/apk/forkRelease/
          signingKeyBase64: ${{ secrets.SIGNING_KEY_BASE64 }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEYSTORE_PASSWORD }}
      - name: Archive arm64 apk
        uses: actions/upload-artifact@v2
        with:
          name: app-arm64-v8a-debug.apk
          path: app/build/outputs/apk/debug/app-arm64-v8a-debug.apk
      - name: Archive armeabi apk
        uses: actions/upload-artifact@v2
        with:
          name: app-armeabi-v7a-forkRelease.apk
          path: app/build/outputs/apk/debug/app-armeabi-v7a-debug.apk
      - name: Archive x86 apk
        uses: actions/upload-artifact@v2
        with:
          name: app-x86-forkRelease.apk
          path: app/build/outputs/apk/debug/app-x86-debug.apk
      - name: Archive x86_64 apk
        uses: actions/upload-artifact@v2
        with:
          name: app-x86_64-forkRelease.apk
          path: app/build/outputs/apk/debug/app-x86_64-debug.apk
